---
title: "Econ 293 Final Project Analysis Report"
author: 
- Chris Lin, Joseph Son
- (clin17@stanford.edu, joeson@stanford.edu)
date: '`r Sys.Date()`'
output: pdf_document
---


```{r load_process_data, warning=FALSE, message=FALSE}
# Set up data and global variables
source("helpers.R")
source("load-data.R")
data_01 <- split_control_treated(0, 1, df, covariate_names)
data_02 <- split_control_treated(0, 2, df, covariate_names)
data_03 <- split_control_treated(0, 3, df, covariate_names)
NUM_TREES <- 1000
```

```{r hte_forests, warning=FALSE, message=FALSE}
# Estimate HTEs using forest-based learners
if (!file.exists("results/results_forests.rds")) {
  set.seed(123)
  results_forests_01 <- compare_forests(data_01$X, data_01$W, data_01$Y, data_01$ID, NUM_TREES)
  results_forests_01$compare <- "0 vs 1"
  
  results_forests_02 <- compare_forests(data_02$X, data_02$W, data_02$Y, data_02$ID, NUM_TREES)
  results_forests_02$compare <- "0 vs 2"
  
  results_forests_03 <- compare_forests(data_03$X, data_03$W, data_03$Y, data_03$ID, NUM_TREES)
  results_forests_03$compare <- "0 vs 3"
  
  results_forests <- Reduce(rbind, list(results_forests_01, 
                                        results_forests_02, 
                                        results_forests_03))
  saveRDS(results_forests, file = "results/results_forests.rds")
} else {
  results_forests <- readRDS(file = "results/results_forests.rds")
}
```

```{r hte_glmnets, warning=FALSE, message=FALSE}
# Estimate HTEs using ridge-based learners
if (!file.exists("results/results_glmnets.rds")) {
  set.seed(1234)
  results_glmnets_01 <- compare_glmnets(data_01$X, data_01$W, data_01$Y, data_01$ID, 10, 0, NUM_TREES)
  results_glmnets_01$compare <- "0 vs 1"
  
  results_glmnets_02 <- compare_glmnets(data_02$X, data_02$W, data_02$Y, data_02$ID, 10, 0, NUM_TREES)
  results_glmnets_02$compare <- "0 vs 2"
  
  results_glmnets_03 <- compare_glmnets(data_03$X, data_03$W, data_03$Y, data_03$ID, 10, 0, NUM_TREES)
  results_glmnets_03$compare <- "0 vs 3"
  
  results_glmnets <- Reduce(rbind, list(results_glmnets_01, 
                                        results_glmnets_02, 
                                        results_glmnets_03))
  saveRDS(results_glmnets, file = "results/results_glmnets.rds")
} else {
  results_glmnets <- readRDS(file = "results/results_glmnets.rds")
}
```

```{r summarize_hte_learners, warning=FALSE, message=FALSE}
# Combine all the results
hte_results <- rbind(results_forests, results_glmnets)

# Summarize the learner results
hte_summary_01 <- summarize_hte_results(hte_results, "0 vs 1")
hte_summary_02 <- summarize_hte_results(hte_results, "0 vs 2")
hte_summary_03 <- summarize_hte_results(hte_results, "0 vs 3")

# Print out the results
cat("0 vs 1", "\n")
hte_summary_01$MRL <- scientific(hte_summary_01$MRL)
hte_summary_01$SDRL <- scientific(hte_summary_01$SDRL)
print(hte_summary_01)
cat("\n\n\n")

cat("0 vs 2", "\n")
hte_summary_02$MRL <- scientific(hte_summary_02$MRL)
hte_summary_02$SDRL <- scientific(hte_summary_02$SDRL)
print(hte_summary_02)
cat("\n\n\n")

cat("0 vs 3", "\n")
hte_summary_03$MRL <- scientific(hte_summary_03$MRL)
hte_summary_03$SDRL <- scientific(hte_summary_03$SDRL)
print(hte_summary_03)
cat("\n\n\n")
```

```{r best_hte_learners, warning=FALSE, message=FALSE}
# Find the best learners
hte_best_01 <- hte_results %>% 
  filter(compare == "0 vs 1") %>% 
  filter(learner == hte_summary_01$learner[hte_summary_01$MRL == min(hte_summary_01$MRL)])
hte_best_learner_01 <- unique(hte_best_01$learner)
print(paste0("Best learner for 0 vs 1: ", hte_best_learner_01))

hte_best_02 <- hte_results %>% 
  filter(compare == "0 vs 2") %>% 
  filter(learner == hte_summary_02$learner[hte_summary_02$MRL == min(hte_summary_02$MRL)])
hte_best_learner_02 <- unique(hte_best_02$learner)
print(paste0("Best learner for 0 vs 2: ", hte_best_learner_02))

hte_best_03 <- hte_results %>% 
  filter(compare == "0 vs 3") %>%
  filter(learner == hte_summary_03$learner[hte_summary_03$MRL == min(hte_summary_03$MRL)])
hte_best_leanrer_03 <- unique(hte_best_03$learner)
print(paste0("Best learner for 0 vs 3: ", hte_best_leanrer_03))
```

```{r plot_cate_dist, warning=FALSE, message=FALSE, fig.width=9, fig.height=4}
par(mfrow = c(1, 3))
hist(hte_best_01$estimate, breaks = 250, ylim = c(0, 1400), xlab = "Estimated CATE (X-ridge)", main = "Matching 1:1")
hist(hte_best_02$estimate, breaks = 250, ylim = c(0, 1400), xlab = "Estimated CATE (X-ridge)", main = "Matching 2:1")
hist(hte_best_03$estimate, breaks = 250, ylim = c(0, 1400), xlab = "Estimated CATE (X-forest)", main = "Matching 3:1")
```

```{r test_overall_hetero, warning=FALSE, message=FALSE}
# Hypothesis test for overall treatment heterogeneity
if (!file.exists("results/test_hetero_summary_01.rds")) {
  test_hetero_01 <- test_hetero(as.matrix(hte_best_01[ , covariate_names]), hte_best_01$W, 
                                hte_best_01$Y, hte_best_01$estimate, NUM_TREES)
  test_hetero_summary_01 <- summarize_test_hetero(test_hetero_01)
  saveRDS(test_hetero_summary_01, file = "results/test_hetero_summary_01.rds")
} else {
  test_hetero_summary_01 <- readRDS("results/test_hetero_summary_01.rds")
}


if (!file.exists("results/test_hetero_summary_02.rds")) {
  test_hetero_02 <- test_hetero(as.matrix(hte_best_02[ , covariate_names]), hte_best_02$W, 
                                hte_best_02$Y, hte_best_02$estimate, NUM_TREES)
  test_hetero_summary_02 <- summarize_test_hetero(test_hetero_02)
  saveRDS(test_hetero_summary_02, file = "results/test_hetero_summary_02.rds")
} else {
  test_hetero_summary_02 <- readRDS("results/test_hetero_summary_02.rds")
}


if (!file.exists("results/test_hetero_summary_03.rds")) {
  test_hetero_03 <- test_hetero(as.matrix(hte_best_03[ , covariate_names]), hte_best_03$W, 
                                hte_best_03$Y, hte_best_03$estimate, NUM_TREES)
  test_hetero_summary_03 <- summarize_test_hetero(test_hetero_03)
  saveRDS(test_hetero_summary_03, file = "results/test_hetero_summary_03.rds")
} else {
  test_hetero_summary_03 <- readRDS("results/test_hetero_summary_03.rds")
}
```

```{r policy, warning=FALSE, message=FALSE}
# Fit the models and get results
donate_cost_ratio <- c(10, 100, 1000, 10000)
costs <- 1 / donate_cost_ratio
if (!file.exists("results/policy_results_03.rds")) {
  set.seed(123)
  policy_results_03 <- list()
  for (i in 1:length(costs)) {
    policy_results_03[[i]] <- opt_policy_forest(data_03$X, data_03$W, data_03$Y, hte_best_03$estimate, data_03$ID, 
                                                cost = costs[i], k = 10, num_trees = NUM_TREES)
  }
  saveRDS(policy_results_03, file = "results/policy_results_03.rds") 
} else {
  policy_results_03 <- readRDS("results/policy_results_03.rds")
}

# Result summaries
policy_summary_dfs <- list()
for (i in 1:length(costs)) {
  policy_summary_dfs[[i]] <- summarize_opt_policy(policy_results_03[[i]]$Ahats_test)
  print(paste0("Donation:cost ratio = ", donate_cost_ratio[i]))
  print(policy_summary_dfs[[i]])
}
```

```{r ATE, warning=FALSE, message=FALSE}
df1 <- data_01$df %>% select(-ID)
df2 <- data_02$df %>% select(-ID)
df3 <- data_03$df %>% select(-ID)

if (!file.exists("results/ate_results_table.rds")) {
  ate_results <- calculate_ATE(df1, df2, df3, 1)
  saveRDS(ate_results, file = "results/ate_results_table.rds")
} else {
  ate_results <- readRDS("results/ate_results_table.rds")
}

if (!file.exists("results/ate_results_reduced_table.rds")) {
  ate_results_reduced <- calculate_ATE(df1, df2, df3, 0.5)
  saveRDS(ate_results_reduced, file = "results/ate_results_reduced_table.rds")
} else {
  ate_results_reduced <- readRDS("results/ate_results_reduced_table.rds")
}
print(ate_results)
print(ate_results_reduced)
```

```{r plot_ATE_estimates, warning=FALSE, message=FALSE, fig.width=9, fig.height=4}
ate_results$Estimator <- factor(ate_results$Estimator, levels = ate_results$Estimator)
ate_results_reduced$Estimator <- factor(ate_results_reduced$Estimator, levels = ate_results_reduced$Estimator)
plot_ATE_estimates(ate_results)
plot_ATE_estimates(ate_results_reduced)
```

```{r plot_calibration, warning=FALSE, message=FALSE, fig.width=9, fig.height=4}
p_logistic1 = p_logistic(df1)
p_logistic2 = p_logistic(df2)
p_logistic3 = p_logistic(df3)
par(mfrow = c(1, 3))
plot_calibration(p_logistic1, df1$W, ylab = "Average treatment", xlab = "Estimated propensity", 
                 xlim = c(0.36, 0.44), main = "Matching 1:1")
plot_calibration(p_logistic2, df2$W, ylab = "Average treatment", xlab = "Estimated propensity", 
                 xlim = c(0.36, 0.44), main = "Matching 2:1")
plot_calibration(p_logistic3, df3$W, ylab = "Average treatment", xlab = "Estimated propensity", 
                 xlim = c(0.36, 0.44), main = "Matching 3:1")
```

```{r plot_propensities, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=8.5}
par(mfrow=c(3,3))
plot_yx(p_logistic(data_01$df), data_01$df$pblack, "Estimated propensity", "Proportion black", main = "Matching 1:1")
plot_yx(p_logistic(data_01$df), data_01$df$median_hhincome, "Estimated propensity", "Median household income")
plot_yx(p_logistic(data_01$df), as.factor(data_01$df$red0), "Estimated propensity", "Living in red state", 
        names = c("No", "Yes"))

plot_yx(p_logistic(data_02$df), data_02$df$pblack, "Estimated propensity", "Proportion black", main = "Matching 2:1")
plot_yx(p_logistic(data_02$df), data_02$df$median_hhincome, "Estimated propensity", "Median household income")
plot_yx(p_logistic(data_02$df), as.factor(data_02$df$red0), "Estimated propensity", "Living in red state", 
        names = c("No", "Yes"))

plot_yx(p_logistic(data_03$df), data_03$df$pblack, "Estimated propensity", "Proportion black", main = "Matching 3:1")
plot_yx(p_logistic(data_03$df), data_03$df$median_hhincome, "Estimated propensity", "Median household income")
plot_yx(p_logistic(data_03$df), as.factor(data_03$df$red0), "Estimated propensity", "Living in red state", 
        names = c("No", "Yes"))
```

```{r plot_CATE, warning=FALSE, message=FALSE, fig.width=8.5, fig.height=8.5}
par(mfrow=c(3,3))
plot_yx(hte_best_01$estimate, hte_best_01$pblack, "Estimated CATE (X-ridge)", "Proportion black", main = "Matching 1:1")
plot_yx(hte_best_01$estimate, hte_best_01$median_hhincome, "Estimated CATE (X-ridge)", "Median household income")
plot_yx(hte_best_01$estimate, as.factor(hte_best_01$red0), "Estimated CATE (X-ridge)", "Living in red state", 
        names = c("No", "Yes"))

plot_yx(hte_best_02$estimate, hte_best_02$pblack, "Estimated CATE (X-ridge)", "Proportion black", main = "Matching 2:1")
plot_yx(hte_best_02$estimate, hte_best_02$median_hhincome, "Estimated CATE (X-ridge)", "Median household income")
plot_yx(hte_best_02$estimate, as.factor(hte_best_02$red0), "Estimated CATE (X-ridge)", "Living in red state", 
        names = c("No", "Yes"))

plot_yx(hte_best_03$estimate, hte_best_03$pblack, "Estimated CATE (X-forest)", "Proportion black", main = "Matching 3:1")
plot_yx(hte_best_03$estimate, hte_best_03$median_hhincome, "Estimated CATE (X-forest)", "Median household income")
plot_yx(hte_best_03$estimate, as.factor(hte_best_03$red0), "Estimated CATE (X-forest)", "Living in red state", 
        names = c("No", "Yes"))

```

```{r test_CATE, warning=FALSE, message=FALSE}
# Compute the doubly robust scores
if (!file.exists("results/hte_best_01.rds")) {
  drs_best_01 <- estimate_binary_drs(X_train = as.matrix(hte_best_01[ , covariate_names]), 
                                     W_train = hte_best_01$W, 
                                     Y_train = hte_best_01$Y, 
                                     cate_train = hte_best_01$estimate, 
                                     X_new = NULL, W_new = NULL, Y_new = NULL, cate_new = NULL, 
                                     num_trees = NUM_TREES, compute_new = FALSE)
  hte_best_01$drs <- drs_best_01$train
  saveRDS(hte_best_01, file = "results/hte_best_01.rds")
} else {
  hte_best_01 <- readRDS("results/hte_best_01.rds")
}

if (!file.exists("results/hte_best_02.rds")) {
  drs_best_02 <- estimate_binary_drs(X_train = as.matrix(hte_best_02[ , covariate_names]), 
                                     W_train = hte_best_02$W, 
                                     Y_train = hte_best_02$Y, 
                                     cate_train = hte_best_02$estimate, 
                                     X_new = NULL, W_new = NULL, Y_new = NULL, cate_new = NULL, 
                                     num_trees = NUM_TREES, compute_new = FALSE)
  hte_best_02$drs <- drs_best_02$train
  saveRDS(hte_best_02, file = "results/hte_best_02.rds")
} else {
  hte_best_02 <- readRDS("results/hte_best_02.rds")
}

if (!file.exists("results/hte_best_03.rds")) {
  drs_best_03 <- estimate_binary_drs(X_train = as.matrix(hte_best_03[ , covariate_names]), 
                                     W_train = hte_best_03$W, 
                                     Y_train = hte_best_03$Y, 
                                     cate_train = hte_best_03$estimate, 
                                     X_new = NULL, W_new = NULL, Y_new = NULL, cate_new = NULL, 
                                     num_trees = NUM_TREES, compute_new = FALSE)
  hte_best_03$drs <- drs_best_03$train
  saveRDS(hte_best_03, file = "results/hte_best_03.rds")
} else {
  hte_best_03 <- readRDS("results/hte_best_03.rds")
}

# Formal hypothesis tests
test_covs <- c("pblack", "median_hhincome", "red0")
test_cov_types <- c("continuous", "continuous", "binary")
df_lst <- list("0 vs 1" = hte_best_01, "0 vs 2" = hte_best_02, "0 vs 3" = hte_best_03)
for (comparison in names(df_lst)) {
  for (i in 1:length(test_covs)) {
    cat(paste0("Comparison: ", comparison), "\n")
    cat(paste0("Covariate: ", test_covs[i]), "\n")
    t_test <- test_covariate_hetero(df = df_lst[[comparison]], 
                                    x_name = test_covs[i], 
                                    x_type = test_cov_types[i])
    print(t_test)
    cat("Corrected p-value: ", min(c(t_test$p.value*length(test_covs)*length(df_lst), 1)), "\n\n")
  }
  cat("\n\n\n")
}

# test_CATE(hte_best_01, "estimate", "pblack", "continuous")
# test_CATE(hte_best_01, "estimate", "median_hhincome", "continuous")
# test_CATE(hte_best_01, "estimate", "red0", "factor")
# 
# test_CATE(hte_best_02, "estimate", "pblack", "continuous")
# test_CATE(hte_best_02, "estimate", "median_hhincome", "continuous")
# test_CATE(hte_best_02, "estimate", "red0", "factor")
# 
# test_CATE(hte_best_03, "estimate", "pblack", "continuous")
# test_CATE(hte_best_03, "estimate", "median_hhincome", "continuous")
# test_CATE(hte_best_03, "estimate", "red0", "factor")
```